//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alliance.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alliance.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a world of peace and tranquility, there stands a village at the edge of Alliance continent where all the villagers are young; No one ever makes it past a certain age due to a terrible plague. Once a day, evil beings will infiltrate the village, kill anyone in sight, and then vanish. They show no remorse or sadness, just gleeful smiles as they vicisiously slaughter men, women and children. People of the village are unable to leave due to large gates on the outside built by the evil beings. After many cent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Story {
            get {
                return ResourceManager.GetString("Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! Welcome to Alliance. It is absolutely imperative that you read me and get a few details about the game! If you wish to skip me, and take the fools road down to destruction, just click &quot;Exit&quot; at anytime. Otherwise, keep hitting &quot;Next&quot;..
        /// </summary>
        internal static string Wizard_Part1 {
            get {
                return ResourceManager.GetString("Wizard_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you didn&apos;t read the story, your job is to save the lives of citizens. If you save enough people, the citizens will grow to love you and may even help you out! However, if all the civilians die, it&apos;s game over!.
        /// </summary>
        internal static string Wizard_Part2 {
            get {
                return ResourceManager.GetString("Wizard_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are stationed in the sky watching over a chunk of Alliance continent and you are armed with sky dollars (pretty sweet; I know) and an assortment of weapons (over on the right there)..
        /// </summary>
        internal static string Wizard_Part3 {
            get {
                return ResourceManager.GetString("Wizard_Part3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right now, the invaders are far away (far far far away), but they are rapidly approaching the chunk YOU&apos;RE supposed to be guarding. Don&apos;t worry, they can&apos;t do anything as long as I&apos;m up (aren&apos;t you glad you didn&apos;t click &apos;Exit&apos;). But once I go away, the clock will start ticking..
        /// </summary>
        internal static string Wizard_Part4 {
            get {
                return ResourceManager.GetString("Wizard_Part4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can then either challenge the invaders by using the remaining time to ectoplastransmaterport them here early, or you can wait until they arrive. Either way...look, you have cash, you have weapons. Save the citizens!.
        /// </summary>
        internal static string Wizard_Part5 {
            get {
                return ResourceManager.GetString("Wizard_Part5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh yeah, one last thing. Pressing and holding &quot;P&quot; lets you view the game in &quot;Polygon&quot; mode. &quot;S&quot; sells a selected tower, &quot;U&quot; upgrades a selected tower (as do the buttons), &quot;N&quot; skips to the next wave and &quot;Spacebar&quot; pauses the game. What else...oh yeah. The further along you get, the smarter the invaders get..
        /// </summary>
        internal static string Wizard_Part6 {
            get {
                return ResourceManager.GetString("Wizard_Part6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll be given new weapons to deal with the increasingly intelligent invaders. No one has ever completely stood off ALL of the waves of invaders, but many have at least seen the teleporting ones. YEAH: T-E-L-E-P-O-R-T-I-N-G! Anywho, you can also click and drag to place multiple weapons. It&apos;s okay to hit &quot;Exit&quot; now..
        /// </summary>
        internal static string Wizard_Part7 {
            get {
                return ResourceManager.GetString("Wizard_Part7", resourceCulture);
            }
        }
    }
}
