//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alliance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alliance.ContentResources", typeof(ContentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] bullet {
            get {
                object obj = ResourceManager.GetObject("bullet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ComicSans {
            get {
                object obj = ResourceManager.GetObject("ComicSans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] debri {
            get {
                object obj = ResourceManager.GetObject("debri", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] flame {
            get {
                object obj = ResourceManager.GetObject("flame", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] flamethrower {
            get {
                object obj = ResourceManager.GetObject("flamethrower", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] flamewave {
            get {
                object obj = ResourceManager.GetObject("flamewave", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] fragment {
            get {
                object obj = ResourceManager.GetObject("fragment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Georgia {
            get {
                object obj = ResourceManager.GetObject("Georgia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lightning {
            get {
                object obj = ResourceManager.GetObject("lightning", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] machinegun {
            get {
                object obj = ResourceManager.GetObject("machinegun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] missileLauncher {
            get {
                object obj = ResourceManager.GetObject("missileLauncher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mouse {
            get {
                object obj = ResourceManager.GetObject("mouse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pulse {
            get {
                object obj = ResourceManager.GetObject("pulse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] railgun {
            get {
                object obj = ResourceManager.GetObject("railgun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rocket {
            get {
                object obj = ResourceManager.GetObject("rocket", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] shockwaveGenerator {
            get {
                object obj = ResourceManager.GetObject("shockwaveGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] speedbump {
            get {
                object obj = ResourceManager.GetObject("speedbump", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sprinkler {
            get {
                object obj = ResourceManager.GetObject("sprinkler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Tahoma {
            get {
                object obj = ResourceManager.GetObject("Tahoma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tank {
            get {
                object obj = ResourceManager.GetObject("tank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] teslaCoil {
            get {
                object obj = ResourceManager.GetObject("teslaCoil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] towerBase {
            get {
                object obj = ResourceManager.GetObject("towerBase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] turret {
            get {
                object obj = ResourceManager.GetObject("turret", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Verdana {
            get {
                object obj = ResourceManager.GetObject("Verdana", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wave {
            get {
                object obj = ResourceManager.GetObject("wave", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
